// Copyright F Rank Hunter. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameplayTags.h"

#define GET_GAMEPLAY_TAG(TagName) FGameplayTag::RequestGameplayTag(FName(TEXT(TagName)))


// Player - Attributes ------------------------------------------------------
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_HEALTH								GET_GAMEPLAY_TAG("Player.Status.Health")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_MAXHEALTH							GET_GAMEPLAY_TAG("Player.Status.MaxHealth")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_HEALTH_DAMAGE						GET_GAMEPLAY_TAG("Player.Status.Damage")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_HEALTH_HEALING						GET_GAMEPLAY_TAG("Player.Status.Healing")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_HEALTH_NATURALREGENINITDELAY			GET_GAMEPLAY_TAG("Player.Status.HealthNaturalRegenInitDelay")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_HEALTH_NATURALREGENAMOUNTPERSEC		GET_GAMEPLAY_TAG("Player.Status.HealthNaturalRegenAmountPerSec")

#define GET_GAMEPLAY_TAG_PLAYER_STATUS_STAMINA								GET_GAMEPLAY_TAG("Player.Status.Stamina")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_MAXSTAMINA							GET_GAMEPLAY_TAG("Player.Status.MaxStamina")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_STAMINA_NATURALREGENINITDELAY		GET_GAMEPLAY_TAG("Player.Status.StaminaNaturalRegenInitDelay")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_STAMINA_NATURALREGENAMOUNTPERSEC		GET_GAMEPLAY_TAG("Player.Status.StaminaNaturalRegenAmountPerSec")

#define GET_GAMEPLAY_TAG_PLAYER_STATUS_VITALITY						GET_GAMEPLAY_TAG("Player.Status.Vitality")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_STRENGTH						GET_GAMEPLAY_TAG("Player.Status.Strength")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_ENDURANCE					GET_GAMEPLAY_TAG("Player.Status.Endurance")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_AGILITY						GET_GAMEPLAY_TAG("Player.Status.Agility")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_WILLPOWER					GET_GAMEPLAY_TAG("Player.Status.Willpower")

#define GET_GAMEPLAY_TAG_PLAYER_STATUS_MOVEMENTSPEED				GET_GAMEPLAY_TAG("Player.Status.MovementSpeed")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_DEFENSEPOWER					GET_GAMEPLAY_TAG("Player.Status.DefensePower")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_MININGPOWER					GET_GAMEPLAY_TAG("Player.Status.MiningPower")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_ATTACKPOWER					GET_GAMEPLAY_TAG("Player.Status.AttackPower")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_ATTACKRANGE					GET_GAMEPLAY_TAG("Player.Status.AttackRange")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_ATTACKSPEED					GET_GAMEPLAY_TAG("Player.Status.AttackSpeed")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_CARRYWEIGHT					GET_GAMEPLAY_TAG("Player.Status.CarryWeight")
#define GET_GAMEPLAY_TAG_PLAYER_STATUS_MAXCARRYWEIGHT				GET_GAMEPLAY_TAG("Player.Status.MaxCarryWeight")




// Player - Ability
#define GET_GAMEPLAY_TAG_PLAYER_ABILITY_MOVE				GET_GAMEPLAY_TAG("Player.Ability.Move")
#define GET_GAMEPLAY_TAG_PLAYER_ABILITY_JUMP				GET_GAMEPLAY_TAG("Player.Ability.Jump")
#define	GET_GAMEPLAY_TAG_PLAYER_ABILITY_SPRINT				GET_GAMEPLAY_TAG("Player.Ability.Sprint")
#define	GET_GAMEPLAY_TAG_PLAYER_ABILITY_PREPAREUSEITEM		GET_GAMEPLAY_TAG("Player.Ability.PrePareUseItem")
#define	GET_GAMEPLAY_TAG_PLAYER_ABILITY_DROPITEM			GET_GAMEPLAY_TAG("Player.Ability.DropItem")
#define	GET_GAMEPLAY_TAG_PLAYER_ABILITY_INTERACT			GET_GAMEPLAY_TAG("Player.Ability.Interact")
#define	GET_GAMEPLAY_TAG_PLAYER_ABILITY_CROUCH				GET_GAMEPLAY_TAG("Player.Ability.Crouch")
#define	GET_GAMEPLAY_TAG_PLAYER_ABILITY_SWITCHINGTOOLS		GET_GAMEPLAY_TAG("Player.Ability.SwitchingTools")
#define	GET_GAMEPLAY_TAG_PLAYER_ABILITY_INITATTRIBUTES		GET_GAMEPLAY_TAG("Player.Ability.InitAttributes")
#define	GET_GAMEPLAY_TAG_PLAYER_ABILITY_KNOCKDOWN			GET_GAMEPLAY_TAG("Player.Ability.Knockdown")
#define	GET_GAMEPLAY_TAG_PLAYER_ABILITY_CLOAKING			GET_GAMEPLAY_TAG("Player.Ability.Cloaking")
#define	GET_GAMEPLAY_TAG_PLAYER_ABILITY_FLASHLIGHTON		GET_GAMEPLAY_TAG("Player.Ability.FlashLightOn")
#define	GET_GAMEPLAY_TAG_PLAYER_ABILITY_FLASHLIGHTOFF		GET_GAMEPLAY_TAG("Player.Ability.FlashLightOff")
#define	GET_GAMEPLAY_TAG_PLAYER_ABILITY_PLAYEMOTE			GET_GAMEPLAY_TAG("Player.Ability.PlayEmote")

#define	GET_GAMEPLAY_TAG_PLAYER_ABILITYFAILED_NOSTAMINA		GET_GAMEPLAY_TAG("Player.AbilityFailed.NoStamina")
#define	GET_GAMEPLAY_TAG_PLAYER_ACTION_ATTACKHITCHECK		GET_GAMEPLAY_TAG("Player.Action.CheckAttackHit")


// Player - States
#define	GET_GAMEPLAY_TAG_PLAYER_STATE_ISSPRINTING		GET_GAMEPLAY_TAG("Player.State.IsSprinting")
#define	GET_GAMEPLAY_TAG_PLAYER_STATE_ISEXHAUSTED		GET_GAMEPLAY_TAG("Player.State.IsExhausted")
#define	GET_GAMEPLAY_TAG_PLAYER_STATE_ISDEAD			GET_GAMEPLAY_TAG("Player.State.IsDead")
#define	GET_GAMEPLAY_TAG_PLAYER_STATE_ISCOMFORT			GET_GAMEPLAY_TAG("Player.State.IsComfort")
#define GET_GAMEPLAY_TAG_PLAYER_STATE_ISCROUCHING		GET_GAMEPLAY_TAG("Player.State.IsCrouching")
#define GET_GAMEPLAY_TAG_PLAYER_STATE_ISACTIONOCCUPIED	GET_GAMEPLAY_TAG("Player.State.IsActionOccupied")
#define GET_GAMEPLAY_TAG_PLAYER_STATE_ISCAMERALOCK		GET_GAMEPLAY_TAG("Player.State.IsCameraLock")
#define GET_GAMEPLAY_TAG_PLAYER_STATE_ISUNRECOVABLE		GET_GAMEPLAY_TAG("Player.State.IsUnrecovable")
#define GET_GAMEPLAY_TAG_PLAYER_STATE_ISDAMAGEOVERTIME	GET_GAMEPLAY_TAG("Player.State.IsDamageOverTime")
#define GET_GAMEPLAY_TAG_PLAYER_STATE_ISUNMOVABLE		GET_GAMEPLAY_TAG("Player.State.IsUnmovable")
#define GET_GAMEPLAY_TAG_PLAYER_STATE_ISMOVING			GET_GAMEPLAY_TAG("Player.State.Ismoving")
#define GET_GAMEPLAY_TAG_PLAYER_STATE_ISOBSERVING		GET_GAMEPLAY_TAG("Player.State.IsObserving")
#define GET_GAMEPLAY_TAG_PLAYER_STATE_ISLOOKTERMINAL	GET_GAMEPLAY_TAG("Player.State.IsLookTerminal")
#define GET_GAMEPLAY_TAG_PLAYER_STATE_ISCLOAKING		GET_GAMEPLAY_TAG("Player.State.IsCloaking")
#define GET_GAMEPLAY_TAG_PLAYER_STATE_ISUNSWAPPABLE		GET_GAMEPLAY_TAG("Player.State.IsUnswappable")
#define GET_GAMEPLAY_TAG_PLAYER_STATE_ISPLAYINGEMOTE		GET_GAMEPLAY_TAG("Player.State.IsPlayingEmote")
#define GET_GAMEPLAY_TAG_PLAYER_STATE_CANNOTOPENSTATUS		GET_GAMEPLAY_TAG("Player.State.CannotOpenStatus")
#define GET_GAMEPLAY_TAG_PLAYER_STATE_ISIMMORTAL		GET_GAMEPLAY_TAG("Player.State.IsImmortal")
#define GET_GAMEPLAY_TAG_PLAYER_STATE_ISTINKERON		GET_GAMEPLAY_TAG("Player.State.IsTinkerOn")

// Player - Debuffs
#define	GET_GAMEPLAY_TAG_DEBUFF_KNOCKDOWN					GET_GAMEPLAY_TAG("Debuff.Knockdown")
#define	GET_GAMEPLAY_TAG_DEBUFF_KNOCKDOWN_DURATION			GET_GAMEPLAY_TAG("Debuff.Knockdown.Duration")
#define	GET_GAMEPLAY_TAG_DEBUFF_POISONED					GET_GAMEPLAY_TAG("Debuff.Poisoned")
#define	GET_GAMEPLAY_TAG_DEBUFF_POISONED_DAMAGE				GET_GAMEPLAY_TAG("Debuff.Poisoned.Damage")
#define	GET_GAMEPLAY_TAG_DEBUFF_POISONED_DURATION			GET_GAMEPLAY_TAG("Debuff.Poisoned.Duration")
#define	GET_GAMEPLAY_TAG_DEBUFF_RESTRICTED					GET_GAMEPLAY_TAG("Debuff.Restricted")
#define	GET_GAMEPLAY_TAG_DEBUFF_RESTRICTED_DURATION			GET_GAMEPLAY_TAG("Debuff.Restricted.Duration")
#define	GET_GAMEPLAY_TAG_DEBUFF_SLOW						GET_GAMEPLAY_TAG("Debuff.Slow")
#define	GET_GAMEPLAY_TAG_DEBUFF_SLOW_DURATION				GET_GAMEPLAY_TAG("Debuff.Slow.Duration")
#define	GET_GAMEPLAY_TAG_DEBUFF_SLOW_SCALE					GET_GAMEPLAY_TAG("Debuff.Slow.Scale")
#define	GET_GAMEPLAY_TAG_DEBUFF_STUN						GET_GAMEPLAY_TAG("Debuff.Stun")
#define	GET_GAMEPLAY_TAG_DEBUFF_STUN_DURATION				GET_GAMEPLAY_TAG("Debuff.Stun.Duration")


// Player - Skills
#define GET_GAMEPLAY_TAG_SKILL								GET_GAMEPLAY_TAG("Player.Skill")
#define GET_GAMEPLAY_TAG_SKILL_PASSIVE						GET_GAMEPLAY_TAG("Player.Skill.Passive")
#define GET_GAMEPLAY_TAG_SKILL_GOMULSANG					GET_GAMEPLAY_TAG("Player.Skill.GoMulSang")
#define GET_GAMEPLAY_TAG_SKILL_TINKER						GET_GAMEPLAY_TAG("Player.Skill.Tinker")
#define GET_GAMEPLAY_TAG_SKILL_ALCHEMIST					GET_GAMEPLAY_TAG("Player.Skill.Alchemist")
#define GET_GAMEPLAY_TAG_SKILL_BREATHER						GET_GAMEPLAY_TAG("Player.Skill.Breather")
#define GET_GAMEPLAY_TAG_SKILL_BREAKER						GET_GAMEPLAY_TAG("Player.Skill.Breaker")
#define GET_GAMEPLAY_TAG_SKILL_BALANCER						GET_GAMEPLAY_TAG("Player.Skill.Balancer")
#define GET_GAMEPLAY_TAG_SKILL_SEEKER						GET_GAMEPLAY_TAG("Player.Skill.Seeker")
#define GET_GAMEPLAY_TAG_SKILL_STOPPER						GET_GAMEPLAY_TAG("Player.Skill.Stopper")

// Player - Cooldown
#define GET_GAMEPLAY_TAG_PLAYER_COOLDOWN_CLOAKING			GET_GAMEPLAY_TAG("Player.Cooldown.Cloaking")
#define GET_GAMEPLAY_TAG_PLAYER_COOLDOWN_ACTIVESKILL		GET_GAMEPLAY_TAG("Player.Cooldown.ActiveSkill")
#define GET_GAMEPLAY_TAG_PLAYER_COOLDOWN_JUMP				GET_GAMEPLAY_TAG("Player.Cooldown.Jump")


// Creature
#define	GET_GAMEPLAY_TAG_CREATURE_ABILITY_ATTACK		GET_GAMEPLAY_TAG("Creature.Ability.Attack")
#define	GET_GAMEPLAY_TAG_CREATURE_STATE_DEATH			GET_GAMEPLAY_TAG("Creature.State.Death")
#define	GET_GAMEPLAY_TAG_CREATURE_STATE_STUN			GET_GAMEPLAY_TAG("Creature.State.Stun")
#define	GET_GAMEPLAY_TAG_CREATURE_STATE_DETECTED		GET_GAMEPLAY_TAG("Creature.State.Detected")


// Commons ------------------------------------------------------------
#define	GET_GAMEPLAY_TAG_COMMON_DAMAGE				GET_GAMEPLAY_TAG("Common.Damage")


// ActorTypes ------------------------------------------------------------
#define	GET_GAMEPLAY_TAG_ACTORTYPE_CREATURE			GET_GAMEPLAY_TAG("ActorType.Creature")
#define	GET_GAMEPLAY_TAG_ACTORTYPE_MAGICSTONE		GET_GAMEPLAY_TAG("ActorType.MagicStone")
#define	GET_GAMEPLAY_TAG_ACTORTYPE_PLAYER			GET_GAMEPLAY_TAG("ActorType.Player")


// GamePlayEvent ------------------------------------------------------------
#define	GET_GAMEPLAY_TAG_GAMEPLAYEVENT_DEATH			GET_GAMEPLAY_TAG("GamePlayEvent.Death")
#define	GET_GAMEPLAY_TAG_GAMEPLAYEVENT_HIT				GET_GAMEPLAY_TAG("GamePlayEvent.Hit")
#define	GET_GAMEPLAY_TAG_GAMEPLAYEVENT_CONSUMECONDITION GET_GAMEPLAY_TAG("GamePlayEvent.ConsumeCondition")
#define	GET_GAMEPLAY_TAG_GAMEPLAYEVENT_COLLISIONCHECK	GET_GAMEPLAY_TAG("GamePlayEvent.CollisionCheck")



// GameplayCue --------------------------------------------------------------
#define GET_GAMEPLAY_TAG_GAMEPLAYCUE_PLAYER_CANCELMONTAGE		GET_GAMEPLAY_TAG("GameplayCue.Player.CancelMontage")
#define GET_GAMEPLAY_TAG_GAMEPLAYCUE_PLAYER_ATTACK_READY		GET_GAMEPLAY_TAG("GameplayCue.Player.Attack.Ready")
#define GET_GAMEPLAY_TAG_GAMEPLAYCUE_PLAYER_ATTACK_SWING		GET_GAMEPLAY_TAG("GameplayCue.Player.Attack.Swing")
#define GET_GAMEPLAY_TAG_GAMEPLAYCUE_PLAYER_TERMINAL_CLOSE		GET_GAMEPLAY_TAG("GameplayCue.Player.Terminal.Close")
#define GET_GAMEPLAY_TAG_GAMEPLAYCUE_PLAYER_TERMINAL_OPEN		GET_GAMEPLAY_TAG("GameplayCue.Player.Terminal.Open")


#define GET_GAMEPLAY_TAG_GAMEPLAYCUE_HIT_MAGICSTONE			GET_GAMEPLAY_TAG("GameplayCue.Hit.MagicStone")
#define GET_GAMEPLAY_TAG_GAMEPLAYCUE_HIT_METAL				GET_GAMEPLAY_TAG("GameplayCue.Hit.Metal")
#define GET_GAMEPLAY_TAG_GAMEPLAYCUE_HIT_WOOD				GET_GAMEPLAY_TAG("GameplayCue.Hit.Wood")